### ISSUE TITLE
app.db & IndexedDb Files

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TrevorDArcyEvans/BlazorSQLiteWasm#1]
Hello! Firstly, thank you for the sample code which helped me to setup sqlite on my application.

Do you happen to know why are both `DemoData.db` and IndexedDb `Files` required? Also, why is there a need to run the following [code](https://github.com/TrevorDArcyEvans/BlazorSQLiteWasm/blob/master/wwwroot/dbstorage.js#L17-L27) every second?

I understand that your codebase is largely adapted from Steve Sanderson's one, but I'm just wondering if you happen to have any insight on these. Thank you!

**Comment by odyyudah** [comment]
Hi, I am also interested in this code.
May I answer your question?
DemoData.db is the SQLite data file which contain car data. 
And DemoData.db will be stored in IndexedDB Files.
you can see the Files in binary format clearly if you run the app and press F12 on Chrome, and go to tab Application and the go to inside menu IndexedDB.
dbstorage.js should not be run every second, but in Steve Sandersson's use case, then dbstorage.js should be run every second because Steve was going to sync the data every second.
Hopefully it will answer your question.

I have a question, if I added two more properties to Car class, the application will throw EF Core exception.
Does anyone know how did this happen?

thank you.

**Comment by Zhiyuan-Amos** [comment]
Hi @odyyudah! Thanks for replying.

> you can see the Files in binary format clearly if you run the app and press F12 on Chrome, and go to tab Application and the go to inside menu IndexedDB.

Yes I am aware of this. However, this is the part I'm not too sure about:

> DemoData.db is the SQLite data file which contain car data.
> And DemoData.db will be stored in IndexedDB Files.

Seems weird from the code [here](https://github.com/TrevorDArcyEvans/BlazorSQLiteWasm/blob/master/wwwroot/dbstorage.js#L9-L11) that we are reading from IndexedDB Files and writing to `DemoData.db`.

> dbstorage.js should not be run every second, but in Steve Sandersson's use case, then dbstorage.js should be run every second because Steve was going to sync the data every second.

nice, gotcha, thanks!

> I have a question, if I added two more properties to Car class, the application will throw EF Core exception.
> Does anyone know how did this happen?

It could be because the database columns aren't updated. You could run

```
await db.Database.EnsureDeletedAsync();
await db.Database.EnsureCreatedAsync();
```

to rebuild the database if you are just doing this for testing. For production, you could follow the guide [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime)

**Comment by TrevorDArcyEvans** [comment]
Thanks to both of you for the comments and analysis.  I will add these to the README.md file soonish.

**Comment by TrevorDArcyEvans** [comment]
This has now been added to the documentation.  Thanks again for your input.

**Comment by odyyudah** [comment]
I think now I get the point what @Zhiyuan-Amos mentioned above.
using F12, I go to Application Tab, Expand the IndexedDB and click delete IndexedDB.
Still the WASM is running fine, can add and delete data. 
So why do we need [dbstorage.js](https://github.com/TrevorDArcyEvans/BlazorSQLiteWasm/blob/master/wwwroot/dbstorage.js) and this [code](https://github.com/TrevorDArcyEvans/BlazorSQLiteWasm/blob/4eba5718cf0c8dd66ef1bf0133ca875d08b5b4cb/Pages/Demo.razor.cs#L32) ?

Thank you
